### ISSUE TITLE
Does UniversalProbeFinder accept phy sorted spikes data, while using KS ephys loader option?

### ISSUE THREAD

**Issue by aloksneurobot1** [JorritMontijn/UniversalProbeFinder#3]
Hi Jorrit, 
the whole software worked smoothly when we upload the KS extracted spike sorting files (without moving to manually sort them using phy).  However, we faced a mismatch in the data loaded from phy sorted/saved data :

 the function EL_PrepEphys_KS had sEphysData.templateAmps (546X1)  field was mismatching from cluster_id (537 X 1). 

![sEphysData spikeAmps mismatch sEphysData cluster_id](https://user-images.githubusercontent.com/26633146/177767794-7b5cc035-6e1a-44de-a4e1-619fa5512c76.PNG)
![error_matlab command window](https://user-images.githubusercontent.com/26633146/177767802-bba97f12-4dee-489b-8773-0b704b4ca7c9.PNG)

Could you guide us to what could be source of this issue?

**Comment by JorritMontijn** [comment]
Hi aloksneurobot1,

I read the cluster ids, labels and quality from cluster_ContamPct.tsv and cluster_KSlabel.tsv, but it seems these are not updated by phy. Since I don't use phy myself, I havent's encountered this error before, so apologies for the inconvenience! I've now added a potential fix that removes the cluster ids that are not in the phy files. Could you check if this solves the problem?

Best,
Jorrit

**Comment by JorritMontijn** [comment]
v1.1 now uses the same cluster_id entries as any .tsv file that is in your ephys folder, and it shows a warning if any tsv file entry numbers don't match, so you can check what's going on. This update should fix any problems with cluster matching, as I agree the previous way I did things was prone to errors. Let me know if you're still experiencing problems though!
