### ISSUE TITLE
error while running Slice Finder

### ISSUE THREAD

**Issue by KacperKon** [JorritMontijn/UniversalProbeFinder#5]
Hi and first of all - thanks for your contribution!

Unfortunately, when I'm trying to run the Slice Finder (Windows, Matlab 2017a), after loading the atlas and preprocessed images I'm getting this error:

"Error using axes
There is no Colormap property on the Axes class.
Error in SF_GenSliceFinderGUI (line 126)
	hAxSliceOverlay = axes(hMain,'Position',[0.5 0 0.5 0.77],'Colormap',sAtlas.ColorMap);
Error in SliceFinder (line 68)
	SF_GenSliceFinderGUI(sAtlas,sSliceData);"

I should also mention that I'm using some version of Allen Atlas that I downloaded 2 years ago to work with the Sharp-Track. I tried to update it to check if this might be causing issues, but the link to the atlas from the Cortex Lab webpage doesn't work.

**Comment by JorritMontijn** [comment]
Hi KacperKon,

Thank you for your message. Your error is caused by your version being outdated. Matlab version 2017a is unfortunately not supported, as (among other things), it cannot use multiple color maps per figure.

You have 3 options:
1) Upgrade to matlab 2019b or later
2) Remove the colormap parameter from this line (and any others you may encounter), so the line becomes: "hAxSliceOverlay = axes(hMain,'Position',[0.5 0 0.5 0.77]);" This will change the colors of the areas in the Allen Brain Atlas, however.
3) Install the stand-alone MCR version. You can find the releases on the right when you go to the "Code" tab.

Best,
Jorrit

**Comment by KacperKon** [comment]
Thanks! Indeed, if I delete the colormap parameter it works.
Best,
Kacper
